title: Choi Seong Hee
description: Game Client Programmer
site_title: 'portfolio - Choi SeongHee'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: twiceChoi
blog_url:
email: chltjdgml51@naver.com
keybase_username: 
twitter_username: 
reddit_username: 

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 